# permissions for end users to edit clusterdecisionresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterdecisionresource-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cdr-operator
    app.kubernetes.io/part-of: cdr-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterdecisionresource-editor-role
rules:
- apiGroups:
  - argo.generators.bashkimkasa
  resources:
  - clusterdecisionresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argo.generators.bashkimkasa
  resources:
  - clusterdecisionresources/status
  verbs:
  - get
