---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - argo.generators.bashkimkasa
  resources:
  - clusterdecisionresources
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argo.generators.bashkimkasa
  resources:
  - clusterdecisionresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
