## Append samples you want in your CSV to this file as resources ##
resources:
- argo.generators_v1alpha1_clusterdecisionresource.yaml
- argo_cluster_configmap.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
